//! Export the live board as a [`horizon-server`] configuration file.
//!
//! horizon-server is a standalone PTY streaming server that serves a
//! browser terminal UI (useful for watching panels on a phone). Its
//! `config.yml` declares workspaces of named panels; this module
//! generates that file from the current board so the same panels can be
//! spawned and streamed server-side.
//!
//! [`horizon-server`]: https://github.com/peters/horizon-server

use std::collections::HashSet;
use std::fmt::Write as _;

use crate::agent_definition;
use crate::board::Board;
use crate::panel::{Panel, PanelKind, default_shell};

/// horizon-server accepts 1-64 characters of `A-Z`, `a-z`, `0-9`, `.`, `_`,
/// and `-` for workspace and panel names.
const MAX_NAME_LEN: usize = 64;

/// The generated horizon-server config, with counts for user feedback.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HorizonServerConfigExport {
    /// Ready-to-write YAML content.
    pub yaml: String,
    /// Number of exported panels.
    pub panels: usize,
    /// Number of exported workspaces.
    pub workspaces: usize,
}

impl Board {
    /// Serializes the board into a horizon-server YAML config.
    ///
    /// Only terminal panels with a known launch command are exported; UI
    /// panels (editor, git changes, usage) and panels without launch
    /// metadata are skipped, as are workspaces left empty by that filter.
    /// Returns `None` when nothing exportable remains.
    #[must_use]
    pub fn to_horizon_server_config(&self) -> Option<HorizonServerConfigExport> {
        let mut body = String::new();
        let mut seen_workspace_names = HashSet::new();
        let mut seen_panel_names = HashSet::new();
        let mut exported_workspaces = 0usize;
        let mut exported_panels = 0usize;

        for workspace in &self.workspaces {
            let exportable: Vec<&Panel> = workspace
                .panels
                .iter()
                .filter_map(|id| self.panel(*id))
                .filter(|panel| is_exportable_panel(panel))
                .collect();
            if exportable.is_empty() {
                continue;
            }
            if exported_workspaces > 0 {
                body.push('\n');
            }
            let base = sanitize_name(&workspace.name).unwrap_or_else(|| "workspace".to_string());
            let workspace_name = unique_name(&mut seen_workspace_names, base);
            let _ = writeln!(body, "  - name: {}", yaml_scalar(&workspace_name));
            let _ = writeln!(body, "    panels:");
            for panel in exportable {
                let base = match panel.custom_name() {
                    Some(name) => name.to_string(),
                    None => panel.kind.display_name().to_string(),
                };
                let name = unique_name(
                    &mut seen_panel_names,
                    sanitize_name(&base).unwrap_or_else(|| "panel".to_string()),
                );
                write_panel(&mut body, &name, panel);
                exported_panels += 1;
            }
            exported_workspaces += 1;
        }

        if exported_panels == 0 {
            return None;
        }

        let mut yaml = String::new();
        let _ = writeln!(yaml, "# Generated by Horizon (Export to Horizon Server).");
        let _ = writeln!(
            yaml,
            "# Point a horizon-server instance at this file to stream these panels."
        );
        let _ = writeln!(yaml, "listen: 127.0.0.1:8080");
        let _ = writeln!(yaml, "token: change-me");
        let _ = writeln!(yaml, "workspaces:");
        yaml.push_str(&body);
        Some(HorizonServerConfigExport {
            yaml,
            panels: exported_panels,
            workspaces: exported_workspaces,
        })
    }
}

/// A panel is exportable when it runs a terminal whose base launch can be
/// resolved; UI-only panels (editor, git changes, usage) are not.
fn is_exportable_panel(panel: &Panel) -> bool {
    panel.content.terminal().is_some() && resolved_server_launch(panel).is_some()
}

/// Resolves the command the server should spawn for this panel.
///
/// User-specified launch metadata wins; plain shells and command panels
/// fall back to the default shell, SSH panels use their connection args,
/// and agent panels fall back to their CLI. Horizon session details
/// (resume ids, plugin dirs) are intentionally not exported: the server
/// starts a fresh session of the same kind.
fn resolved_server_launch(panel: &Panel) -> Option<(String, Vec<String>)> {
    let command = panel.launch_command.clone();
    let args = panel.launch_args.clone();
    let (program, args) = match panel.kind {
        PanelKind::Editor | PanelKind::GitChanges | PanelKind::Usage => return None,
        PanelKind::Shell | PanelKind::Command => (command.unwrap_or_else(default_shell), args),
        PanelKind::Ssh => match &panel.ssh_connection {
            Some(connection) => ("ssh".to_string(), connection.to_command_args()),
            None => (command.unwrap_or_else(|| "ssh".to_string()), args),
        },
        PanelKind::Codex
        | PanelKind::Claude
        | PanelKind::OpenCode
        | PanelKind::Gemini
        | PanelKind::KiloCode
        | PanelKind::Pi
        | PanelKind::Grok => {
            let definition = agent_definition(panel.kind)?;
            let program = command.unwrap_or_else(|| definition.default_command.to_string());
            (program, args)
        }
    };
    Some((program, args))
}

fn write_panel(body: &mut String, name: &str, panel: &Panel) {
    let Some((command, args)) = resolved_server_launch(panel) else {
        return;
    };
    let _ = writeln!(body, "      - name: {}", yaml_scalar(name));
    let _ = writeln!(body, "        command: {}", yaml_scalar(&command));
    if !args.is_empty() {
        let _ = writeln!(body, "        args:");
        for arg in &args {
            let _ = writeln!(body, "          - {}", yaml_scalar(arg));
        }
    }
    if let Some(cwd) = panel.launch_cwd.as_deref().and_then(std::path::Path::to_str)
        && !cwd.is_empty()
    {
        let _ = writeln!(body, "        cwd: {}", yaml_scalar(cwd));
    }
    if let Some(terminal) = panel.content.terminal() {
        let _ = writeln!(body, "        cols: {}", terminal.cols());
        let _ = writeln!(body, "        rows: {}", terminal.rows());
    }
}

/// Maps an arbitrary display name into the horizon-server name space
/// (1-64 of `A-Z`, `a-z`, `0-9`, `.`, `_`, `-`). Runs of disallowed
/// characters collapse to a single `-`. Returns `None` when the name has
/// no allowed characters at all.
#[must_use]
fn sanitize_name(raw: &str) -> Option<String> {
    let mut out = String::with_capacity(raw.len().min(MAX_NAME_LEN));
    let mut last_hyphen = false;
    for ch in raw.chars() {
        if ch.is_ascii_alphanumeric() || matches!(ch, '.' | '_') {
            out.push(ch);
            last_hyphen = false;
        } else if !out.is_empty() && !last_hyphen {
            out.push('-');
            last_hyphen = true;
        }
    }
    let trimmed = out.trim_end_matches('-');
    if trimmed.is_empty() {
        return None;
    }
    let truncated: String = trimmed.chars().take(MAX_NAME_LEN).collect();
    let result = truncated.trim_end_matches('-');
    (!result.is_empty()).then(|| result.to_string())
}

/// Returns `base` when unseen, otherwise appends `-2`, `-3`, ... (trimming
/// the base so the result stays within the name length limit).
fn unique_name(seen: &mut HashSet<String>, base: String) -> String {
    if seen.insert(base.clone()) {
        return base;
    }
    let mut suffix = 2u32;
    loop {
        let trimmed_base: String = base.chars().take(MAX_NAME_LEN - 10).collect();
        let candidate = format!("{trimmed_base}-{suffix}");
        suffix += 1;
        if seen.insert(candidate.clone()) {
            return candidate;
        }
    }
}

/// Renders a value as a double-quoted YAML scalar. Always quoting keeps
/// values like a bare `~` (null in YAML) or `key: value` intact.
#[must_use]
fn yaml_scalar(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            ch => out.push(ch),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::board::Board;
    use crate::panel::{PanelKind, PanelOptions};

    fn seen(names: &[&str]) -> HashSet<String> {
        names.iter().map(|name| (*name).to_string()).collect()
    }

    #[test]
    fn sanitize_name_collapses_disallowed_characters() {
        assert_eq!(sanitize_name("My Agent").as_deref(), Some("My-Agent"));
        assert_eq!(sanitize_name("ops: logs #1").as_deref(), Some("ops-logs-1"));
        assert_eq!(sanitize_name("a.b_c-d").as_deref(), Some("a.b_c-d"));
        assert_eq!(
            sanitize_name("  leading and trailing  ").as_deref(),
            Some("leading-and-trailing")
        );
    }

    #[test]
    fn sanitize_name_rejects_names_without_allowed_characters() {
        assert_eq!(sanitize_name("///"), None);
        assert_eq!(sanitize_name("é"), None);
        assert_eq!(sanitize_name("🚀 --"), None);
        // Non-ASCII runs are dropped, but any ASCII letters survive.
        assert_eq!(sanitize_name("émoji 🚀").as_deref(), Some("moji"));
    }

    #[test]
    fn sanitize_name_truncates_to_the_name_limit() {
        let long = "a".repeat(120);
        let sanitized = sanitize_name(&long).expect("allowed characters survive");
        assert_eq!(sanitized.len(), MAX_NAME_LEN);
    }

    #[test]
    fn unique_name_suffixed_on_collision() {
        let mut names = seen(&["shell"]);
        assert_eq!(unique_name(&mut names, "shell".to_string()), "shell-2");
        assert_eq!(unique_name(&mut names, "shell".to_string()), "shell-3");
        assert_eq!(unique_name(&mut names, "other".to_string()), "other");
    }

    #[test]
    fn unique_name_stays_within_the_length_limit_for_long_bases() {
        let base = "a".repeat(MAX_NAME_LEN);
        let mut names = seen(&[base.as_str()]);
        let unique = unique_name(&mut names, base);
        assert!(unique.len() <= MAX_NAME_LEN, "got {unique:?}");
    }

    #[test]
    fn yaml_scalar_quotes_and_escapes() {
        assert_eq!(yaml_scalar("~"), r#""~""#);
        assert_eq!(yaml_scalar("say \"hi\""), r#""say \"hi\"""#);
        assert_eq!(yaml_scalar("a\\b"), r#""a\\b""#);
        assert_eq!(yaml_scalar("line\nbreak"), r#""line\nbreak""#);
        assert_eq!(yaml_scalar("key: value"), r#""key: value""#);
    }

    #[test]
    fn export_of_empty_board_is_none() {
        let board = Board::new();
        assert_eq!(board.to_horizon_server_config(), None);
    }

    #[test]
    fn export_covers_workspaces_names_and_launch_metadata() {
        let mut board = Board::new();
        let dev = board.create_workspace("dev tools");
        let shell = board
            .create_panel(PanelOptions::default(), dev)
            .expect("shell panel should spawn");
        let command = board
            .create_panel(
                PanelOptions {
                    name: Some("echo hi".to_string()),
                    command: Some("echo".to_string()),
                    args: vec!["hello world".to_string()],
                    cwd: Some(std::path::PathBuf::from("/tmp")),
                    kind: PanelKind::Command,
                    ..PanelOptions::default()
                },
                dev,
            )
            .expect("command panel should spawn");
        let ops = board.create_workspace("ops");
        board
            .create_panel(
                PanelOptions {
                    kind: PanelKind::Command,
                    command: Some("sleep".to_string()),
                    args: vec!["60".to_string()],
                    ..PanelOptions::default()
                },
                ops,
            )
            .expect("sleep panel should spawn");
        // A workspace whose only panel is not a terminal is omitted.
        let ui = board.create_workspace("ui only");
        board
            .create_panel(
                PanelOptions {
                    kind: PanelKind::Usage,
                    ..PanelOptions::default()
                },
                ui,
            )
            .expect("usage panel should spawn");

        let export = board.to_horizon_server_config().expect("panels exist");
        assert_eq!(export.panels, 3);
        assert_eq!(export.workspaces, 2);

        let yaml = &export.yaml;
        assert!(yaml.starts_with("# Generated by Horizon"), "yaml:\n{yaml}");
        assert!(yaml.contains("listen: 127.0.0.1:8080"));
        assert!(yaml.contains("token: change-me"));
        assert!(yaml.contains("workspaces:"));
        // Workspace names are sanitized; the empty "ui only" workspace is absent.
        assert!(yaml.contains("- name: \"dev-tools\""));
        assert!(yaml.contains("- name: \"ops\""));
        assert!(!yaml.contains("ui-only"));
        // Custom panel name wins, sanitized.
        assert!(yaml.contains("- name: \"echo-hi\""));
        assert!(yaml.contains("command: \"echo\""));
        assert!(yaml.contains("args:"));
        assert!(yaml.contains("- \"hello world\""));
        assert!(yaml.contains("cwd: \"/tmp\""));
        // Shell panel falls back to the kind display name and the
        // resolved default shell as its command.
        assert!(yaml.contains("- name: \"Shell\""));
        let expected_shell = std::env::var("SHELL").unwrap_or_else(|_| {
            if cfg!(target_os = "macos") {
                "/bin/zsh".to_string()
            } else {
                "/bin/bash".to_string()
            }
        });
        assert!(yaml.contains(&format!("command: \"{expected_shell}\"")));
        // cols/rows are emitted for every exported terminal panel.
        assert_eq!(yaml.matches("cols:").count(), 3);
        assert_eq!(yaml.matches("rows:").count(), 3);

        // Deterministic ordering: dev workspace (and its panels) first.
        assert!(yaml.find("dev-tools").unwrap() < yaml.find("\"ops\"").unwrap());
        assert!(yaml.find("echo-hi").unwrap() < yaml.find("\"ops\"").unwrap());

        board.close_panel(shell);
        board.close_panel(command);
    }

    #[test]
    fn export_dedupes_panel_names_globally_but_keeps_workspace_names() {
        let options = |arg: &str| PanelOptions {
            name: Some("same".to_string()),
            command: Some("echo".to_string()),
            args: vec![arg.to_string()],
            kind: PanelKind::Command,
            ..PanelOptions::default()
        };
        let mut board = Board::new();
        let work = board.create_workspace("work");
        let first = board
            .create_panel(options("1"), work)
            .expect("first panel should spawn");
        let second = board
            .create_panel(options("2"), work)
            .expect("second panel should spawn");
        // A workspace that reuses the panel name is legal on the server
        // (separate namespaces), but its panel still gets a fresh suffix.
        let colliding_ws = board.create_workspace("same");
        let third = board
            .create_panel(options("3"), colliding_ws)
            .expect("third panel should spawn");

        let yaml = board.to_horizon_server_config().expect("panels exist").yaml;
        let lines: Vec<&str> = yaml.lines().collect();
        let count_line = |line: &str| lines.iter().filter(|candidate| **candidate == line).count();
        // Workspaces (2-space indent) keep the base name.
        assert_eq!(count_line("  - name: \"same\""), 1);
        // Panels (6-space indent) dedupe globally across workspaces.
        assert_eq!(count_line("      - name: \"same\""), 1);
        assert_eq!(count_line("      - name: \"same-2\""), 1);
        assert_eq!(count_line("      - name: \"same-3\""), 1);

        board.close_panel(first);
        board.close_panel(second);
        board.close_panel(third);
    }
}
